using Atomizer.Models.Base;
using Cronos;

namespace Atomizer;

/// <summary>
/// Represents a recurring job schedule that generates <see cref="AtomizerJob"/> instances on a cron-based interval.
/// </summary>
public class AtomizerSchedule : Model
{
    /// <summary>
    /// Gets or sets the unique key identifying this recurring schedule.
    /// </summary>
    public JobKey JobKey { get; set; } = new JobKey("default");

    /// <summary>
    /// Gets or sets the key of the queue to which generated jobs are added.
    /// </summary>
    public QueueKey QueueKey { get; set; } = QueueKey.Default;

    /// <summary>
    /// Gets or sets the CLR type of the job payload.
    /// </summary>
    public Type? PayloadType { get; set; }

    /// <summary>
    /// Gets or sets the serialized payload passed to each generated job.
    /// </summary>
    public string Payload { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the cron schedule that determines when jobs are generated.
    /// </summary>
    public Schedule Schedule { get; set; } = Schedule.Default;

    /// <summary>
    /// Gets or sets the time zone in which the cron expression is evaluated.
    /// </summary>
    public TimeZoneInfo TimeZone { get; set; } = TimeZoneInfo.Utc;

    /// <summary>
    /// Gets or sets the policy applied when the schedule fires late.
    /// </summary>
    public MisfirePolicy MisfirePolicy { get; set; } = MisfirePolicy.ExecuteNow;

    /// <summary>
    /// Gets or sets the maximum number of missed occurrences to catch up on.
    /// <remarks>Only evaluated when <see cref="MisfirePolicy"/> is set to <see cref="MisfirePolicy.CatchUp"/>. Default is 5.</remarks>
    /// </summary>
    public int MaxCatchUp { get; set; } = 5;

    /// <summary>
    /// Gets or sets a value indicating whether this schedule is active.
    /// </summary>
    public bool Enabled { get; set; } = true;

    /// <summary>
    /// Gets or sets the retry strategy applied to jobs generated by this schedule.
    /// </summary>
    public RetryStrategy RetryStrategy { get; set; } = RetryStrategy.Default;

    /// <summary>
    /// Gets or sets the UTC time at which the next occurrence of this schedule is due.
    /// </summary>
    public DateTimeOffset NextRunAt { get; set; }

    /// <summary>
    /// Gets or sets the UTC time at which the most recent job was enqueued for this schedule.
    /// </summary>
    public DateTimeOffset? LastEnqueueAt { get; set; }

    /// <summary>
    /// Gets or sets the UTC time at which this schedule was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>
    /// Gets or sets the UTC time at which this schedule was last updated.
    /// </summary>
    public DateTimeOffset UpdatedAt { get; set; }

    private CronExpression CronExpression => CronExpression.Parse(Schedule.ToString(), CronFormat.IncludeSeconds);

    /// <summary>
    /// Creates a new <see cref="AtomizerSchedule"/> and computes the initial <see cref="NextRunAt"/>.
    /// </summary>
    /// <param name="jobKey">The unique key identifying this schedule.</param>
    /// <param name="queueKey">The queue to which generated jobs are added.</param>
    /// <param name="payloadType">The CLR type of the job payload.</param>
    /// <param name="payload">The serialized payload for generated jobs.</param>
    /// <param name="schedule">The cron schedule.</param>
    /// <param name="timeZone">The time zone for cron evaluation.</param>
    /// <param name="createdAt">The UTC creation time.</param>
    /// <param name="misfirePolicy">The misfire policy; defaults to <see cref="MisfirePolicy.ExecuteNow"/>.</param>
    /// <param name="maxCatchUp">Maximum catch-up occurrences; defaults to 5.</param>
    /// <param name="enabled">Whether the schedule is initially enabled; defaults to <see langword="true"/>.</param>
    /// <param name="retryStrategy">Optional retry strategy; defaults to <see cref="RetryStrategy.Default"/>.</param>
    /// <returns>A new <see cref="AtomizerSchedule"/> instance.</returns>
    public static AtomizerSchedule Create(
        JobKey jobKey,
        QueueKey queueKey,
        Type payloadType,
        string payload,
        Schedule schedule,
        TimeZoneInfo timeZone,
        DateTimeOffset createdAt,
        MisfirePolicy misfirePolicy = MisfirePolicy.ExecuteNow,
        int maxCatchUp = 5,
        bool enabled = true,
        RetryStrategy? retryStrategy = null
    )
    {
        var atomizerSchedule = new AtomizerSchedule
        {
            Id = Guid.NewGuid(),
            JobKey = jobKey,
            QueueKey = queueKey,
            PayloadType = payloadType,
            Payload = payload,
            Schedule = schedule,
            TimeZone = timeZone,
            MisfirePolicy = misfirePolicy,
            MaxCatchUp = maxCatchUp,
            Enabled = enabled,
            RetryStrategy = retryStrategy ?? RetryStrategy.Default,
            CreatedAt = createdAt,
            UpdatedAt = createdAt,
        };

        atomizerSchedule.NextRunAt =
            atomizerSchedule.CronExpression.GetNextOccurrence(createdAt, timeZone) ?? DateTimeOffset.MaxValue;

        return atomizerSchedule;
    }

    /// <summary>
    /// Returns the list of occurrence timestamps that are due at or before <paramref name="now"/>,
    /// applying the configured <see cref="MisfirePolicy"/>.
    /// </summary>
    /// <param name="now">The current UTC time used to determine due occurrences.</param>
    /// <returns>An ordered list of due occurrence timestamps.</returns>
    public List<DateTimeOffset> GetOccurrences(DateTimeOffset now)
    {
        var occurrences = new List<DateTimeOffset>();

        if (NextRunAt > now)
        {
            return occurrences;
        }

        switch (MisfirePolicy)
        {
            case MisfirePolicy.Ignore:
                break;
            case MisfirePolicy.ExecuteNow:
                occurrences.Add(NextRunAt);
                break;
            case MisfirePolicy.CatchUp:
                occurrences.AddRange(
                    CronExpression
                        .GetOccurrences(LastEnqueueAt ?? CreatedAt, now, TimeZone)
                        .OrderBy(dt => dt)
                        .Take(MaxCatchUp)
                );
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(MisfirePolicy), MisfirePolicy, "Invalid misfire policy");
        }

        return occurrences;
    }

    /// <summary>
    /// Advances <see cref="NextRunAt"/> to the next occurrence after <paramref name="horizon"/>.
    /// </summary>
    /// <param name="horizon">The occurrence time used as the starting point to compute the next run.</param>
    /// <param name="now">The current UTC time, used to update <see cref="UpdatedAt"/>.</param>
    public void UpdateNextOccurence(DateTimeOffset horizon, DateTimeOffset now)
    {
        var nextOccurrence = CronExpression.GetNextOccurrence(horizon, TimeZone);
        NextRunAt = nextOccurrence ?? DateTimeOffset.MaxValue; // No further occurrences
        LastEnqueueAt = horizon;
        UpdatedAt = now;
    }

    /// <summary>
    /// Disables the schedule so it no longer generates jobs.
    /// </summary>
    /// <param name="now">The current UTC time, used to update <see cref="UpdatedAt"/>.</param>
    public void Disable(DateTimeOffset now)
    {
        Enabled = false;
        UpdatedAt = now;
    }
}

/// <summary>
/// Defines the policy applied when a recurring schedule fires after its expected time.
/// </summary>
public enum MisfirePolicy
{
    /// <summary>Skip the missed run and advance to the next scheduled occurrence.</summary>
    Ignore = 1,

    /// <summary>Enqueue one job immediately, then advance to the next scheduled occurrence.</summary>
    ExecuteNow = 2,

    /// <summary>Enqueue all missed occurrences up to <see cref="AtomizerSchedule.MaxCatchUp"/>.</summary>
    CatchUp = 3,
}
