<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>Atomizer.FlowTests</RootNamespace>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>
    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Xunit" />
        <Using Include="AwesomeAssertions" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="AwesomeAssertions" Version="9.4.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.0" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.0" />
        <PackageReference Include="StackExchange.Redis" Version="2.11.3" />
        <PackageReference Include="Testcontainers.MsSql" Version="4.10.0" />
        <PackageReference Include="Testcontainers.MySql" Version="4.10.0" />
        <PackageReference Include="Testcontainers.PostgreSql" Version="4.10.0" />
        <PackageReference Include="Testcontainers.Redis" Version="4.10.0" />
        <PackageReference Include="xunit.v3" Version="2.0.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\Atomizer.EntityFrameworkCore\Atomizer.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\src\Atomizer.Redis\Atomizer.Redis.csproj" />
    </ItemGroup>
</Project>
