<Project>
    <PropertyGroup>
        <Authors>Mikkel Buhl</Authors>
        <PackageProjectUrl>https://github.com/mnbuhl/Atomizer</PackageProjectUrl>
        <RepositoryUrl>https://github.com/mnbuhl/Atomizer</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>logo.png</PackageIcon>
        <Copyright>Copyright © 2025 Mikkel Buhl</Copyright>
        <PackageTags>atomizer;queue;queueing;scheduler;scheduling;jobs;tasks;background</PackageTags>
    </PropertyGroup>
    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="..\..\assets\logo.png" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>
