name: Publish package to NuGet
on:
  workflow_call:
    inputs:
      PACKAGE_ID:
        required: true
        type: string
        description: 'The folder containing the project to publish'
      PACKAGE_VERSION:
        required: true
        type: string
        description: 'The version to publish.'

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
    secrets: inherit
  
  publish:
    runs-on: ubuntu-latest
    needs: verify
    strategy:
      matrix:
        package_id: ${{ fromJson(inputs.PACKAGE_ID) }}
      fail-fast: true
      max-parallel: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Pack NuGet package
        run: dotnet pack --configuration Release src/${{ matrix.package_id }} --output ./artifacts /p:PackageVersion=${{ inputs.PACKAGE_VERSION }} /p:ContinuousIntegrationBuild=true

      - name: Publish NuGet package
        run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate