name: Verify
on:
  push:
    branches: [ main ]
    paths: [ 'src/**', 'tests/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'src/**', 'tests/**' ]
  workflow_dispatch:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --no-restore --configuration Release --verbosity minimal

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release --collect:"XPlat Code Coverage" --logger "trx;LogFileName=TestResults.trx" --results-directory ./TestResults
        
      - name: Report test results
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Test Results
          path: ./TestResults/**/*.trx
          reporter: dotnet-trx
          
      - name: Code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: ${{ !cancelled() }}
        with:
          filename: ./TestResults/**/coverage.cobertura.xml
          format: 'markdown'
          output: 'both'
          badge: true