name: Verify
on:
  push:
    branches: [ main ]
    paths: [ 'src/**', 'tests/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'src/**', 'tests/**' ]
  workflow_dispatch:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            6.0.x
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --no-restore --configuration Release --verbosity minimal

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release --collect:"XPlat Code Coverage" --logger "trx" --results-directory ./TestResults
        
      - name: Test results report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Test Results
          path: ./TestResults/**/*.trx
          reporter: dotnet-trx
          
      - name: Code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: ${{ !cancelled() }}
        with:
          filename: ./TestResults/*/coverage.cobertura.xml
          format: 'markdown'
          output: 'both'
          badge: true
          hide_branch_rate: true
          hide_complexity: true
          
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md